app:
  topology-keys: aws.ap-southeast-1.ap-southeast-1c
  initial-ysql-host: 127.0.0.3
  region: AP

spring:
  datasource:
    hikari:
      connection-test-query: "select * from customers where preferred_region = 'AP' limit 1;"
