app:
  topology-keys: aws.eu-west-1.eu-west-1a
  initial-ysql-host: 127.0.0.2
  region: EU


spring:
  datasource:
    hikari:
      connection-test-query: "select * from customers where preferred_region = 'EU' limit 1;"
