app:
  security:
    jwt:
      secret: cccccclvkgnllrhrngucjbivrehvjcnkfvfihildhfcg
      expiry: 86400
  cors:
    allowed_origins: http://localhost:3000/
    max_age: 3600

spring:
  application:
    name: trading-preferences
  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          provider_disables_autocommit: true
        default_schema: public
    open-in-view: false
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false
      keepalive-time: 120000
      connection-init-sql: "set search_path=public;"
  data:
    rest:
      base-path: /api/v1
  devtools:
    livereload:
      port: 35730

management:
  endpoints:
    web:
      exposure:
        include: "*"



logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org:
      springframework:
        security: DEBUG
