spring:
  application:
    name: trading-preferences
  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        default_schema: public
    open-in-view: false
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false
      keepalive-time: 120000
      connection-init-sql: "set search_path=public;"
  data:
    rest:
      base-path: /api
#  jackson:
#    property-naming-strategy: SNAKE_CASE

springdoc:
  api-docs:
    path: /api-docs


  swagger-ui:
    path: /api-docs.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: "*"
