name: Preferences App CI

on:
  push:
    paths:
      - 'preferences/**'
      - '.github/workflows/preferences-ci.yml'
  workflow_dispatch:


defaults:
  run:
    shell: bash
    working-directory: preferences
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots package verify deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy artifacts
        run: mkdir -p preferences/target/staging && cp preferences/target/*.jar preferences/target/staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: preferences/target/staging
      - name: create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v0.0.1.${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./preferences/target/tradex-0.0.1-SNAPSHOT.jar
          asset_name: tradex-0.0.1-SNAPSHOT.jar
          asset_content_type: application/gzip
